"""
EstimationService — Pure heuristic cost/duration estimator.

100% deterministic, no LLM calls, no DB writes.
Calculates estimated tokens, cost, and duration for a planned Job
based on agent configurations and pre-determined model pricing.

Used by POST /api/v1/jobs/estimate before the user confirms a Job.
"""

from __future__ import annotations

from app.api.schemas.requests import AgentConfigItem, EstimateJobRequest
from app.api.schemas.responses import AgentEstimateItem, JobEstimateResponse

# ── Model Pricing Table (USD per 1K tokens) ───────────────────────────────────
# Source: public pricing pages as of 2024-Q1. Update as needed.

_MODEL_PRICING: dict[str, dict[str, float]] = {
    "gpt-4-turbo":     {"input": 0.01,     "output": 0.03},
    "gpt-4o":          {"input": 0.005,    "output": 0.015},
    "gpt-3.5-turbo":   {"input": 0.0005,   "output": 0.0015},
    "claude-opus-3.5": {"input": 0.015,    "output": 0.075},
    "claude-haiku":    {"input": 0.00025,  "output": 0.00125},
    "claude-sonnet":   {"input": 0.003,    "output": 0.015},
    "llama-3-70b":     {"input": 0.0,      "output": 0.0},
    "llama-3-8b":      {"input": 0.0,      "output": 0.0},
}

# ── Token Heuristics per Agent (for a ~medium repo, ~500 files) ──────────────
# input_tokens: tokens sent to the model (context window usage)
# output_tokens: tokens generated by the model (response)

_AGENT_TOKEN_HEURISTICS: dict[str, dict[str, int]] = {
    "stack_detector":    {"input": 0,      "output": 0,     "duration_s": 120},
    "context_builder":   {"input": 0,      "output": 0,     "duration_s": 180},
    "system_mapper":     {"input": 72_000, "output": 13_000, "duration_s": 600},
    "tech_debt_analyzer":{"input": 25_000, "output": 3_500,  "duration_s": 300},
    "technical_doc_writer": {"input": 8_500, "output": 1_600, "duration_s": 240},
    "human_doc_writer":  {"input": 6_000,  "output": 1_200,  "duration_s": 180},
    "ai_context_writer": {"input": 5_000,  "output": 1_000,  "duration_s": 120},
    "debt_doc_writer":   {"input": 4_000,  "output": 800,    "duration_s": 150},
}

# ── Default models by tier ────────────────────────────────────────────────────

_TIER_DEFAULT_MODELS: dict[str, dict[str, str]] = {
    "budget": {
        "system_mapper": "llama-3-70b",
        "tech_debt_analyzer": "gpt-3.5-turbo",
        "technical_doc_writer": "gpt-3.5-turbo",
        "human_doc_writer": "gpt-3.5-turbo",
        "ai_context_writer": "gpt-3.5-turbo",
        "debt_doc_writer": "gpt-3.5-turbo",
    },
    "standard": {
        "system_mapper": "gpt-4-turbo",
        "tech_debt_analyzer": "claude-haiku",
        "technical_doc_writer": "gpt-3.5-turbo",
        "human_doc_writer": "gpt-3.5-turbo",
        "ai_context_writer": "gpt-3.5-turbo",
        "debt_doc_writer": "claude-haiku",
    },
    "premium": {
        "system_mapper": "claude-opus-3.5",
        "tech_debt_analyzer": "gpt-4-turbo",
        "technical_doc_writer": "gpt-4-turbo",
        "human_doc_writer": "gpt-4-turbo",
        "ai_context_writer": "gpt-4-turbo",
        "debt_doc_writer": "gpt-4-turbo",
    },
}

_AGENT_DISPLAY_NAMES: dict[str, str] = {
    "stack_detector": "Stack Detector",
    "context_builder": "Architecture Context Builder",
    "system_mapper": "System Mapper",
    "tech_debt_analyzer": "Tech Debt Analyzer",
    "technical_doc_writer": "Technical Doc Writer",
    "human_doc_writer": "Human Doc Writer",
    "ai_context_writer": "AI Context Writer",
    "debt_doc_writer": "Debt Doc Writer",
}


def _cost_for_agent(
    agent_id: str,
    model_id: str | None,
) -> tuple[int, int, float]:
    """Return (input_tokens, output_tokens, cost_usd) for one agent."""
    heuristics = _AGENT_TOKEN_HEURISTICS.get(agent_id, {"input": 0, "output": 0})
    input_t = heuristics["input"]
    output_t = heuristics["output"]

    if not model_id or model_id not in _MODEL_PRICING:
        return input_t, output_t, 0.0

    pricing = _MODEL_PRICING[model_id]
    cost = (input_t / 1000 * pricing["input"]) + (output_t / 1000 * pricing["output"])
    return input_t, output_t, round(cost, 4)


def estimate(request: EstimateJobRequest) -> JobEstimateResponse:
    """
    Calculate estimated cost and duration for a planned Job.

    Algorithm:
      1. For each enabled agent, determine which model will be used
         (explicit override > tier default > no model for deterministic agents).
      2. Look up token heuristics for that agent.
      3. Calculate cost using the model pricing table.
      4. Sum totals and generate warnings.
    """
    tier_id = request.tier.value  # budget | standard | premium
    tier_defaults = _TIER_DEFAULT_MODELS.get(tier_id, {})

    # Build a quick lookup of explicit overrides from agent_configs
    config_map: dict[str, AgentConfigItem] = {
        cfg.agent_id: cfg for cfg in request.agent_configs
    }

    # All agent IDs in execution order
    all_agent_ids = list(_AGENT_TOKEN_HEURISTICS.keys())

    breakdown: list[AgentEstimateItem] = []
    total_tokens = 0
    total_cost = 0.0
    total_duration_s = 0
    warnings: list[str] = []

    for agent_id in all_agent_ids:
        cfg = config_map.get(agent_id)
        enabled = cfg.enabled if cfg else True  # enabled by default

        if not enabled:
            continue

        # Resolve model: explicit override → tier default → None (deterministic)
        model_id: str | None = None
        if cfg and cfg.model:
            model_id = cfg.model
        elif agent_id in tier_defaults:
            model_id = tier_defaults[agent_id]

        heuristics = _AGENT_TOKEN_HEURISTICS.get(agent_id, {})
        duration_s = heuristics.get("duration_s", 60)
        input_t, output_t, cost = _cost_for_agent(agent_id, model_id)
        agent_total_tokens = input_t + output_t

        breakdown.append(
            AgentEstimateItem(
                agent_id=agent_id,
                agent_name=_AGENT_DISPLAY_NAMES.get(agent_id, agent_id),
                tokens=agent_total_tokens,
                cost_usd=cost,
                duration_minutes=round(duration_s / 60, 1),
                model=model_id,
            )
        )

        total_tokens += agent_total_tokens
        total_cost += cost
        total_duration_s += duration_s

    # Warnings based on repo characteristics
    if request.repo_url and any(
        kw in request.repo_url.lower()
        for kw in ["monorepo", "enterprise", "platform"]
    ):
        warnings.append(
            "Repository name suggests a large codebase. "
            "Analysis may take longer than estimated."
        )

    if total_cost > 10.0:
        warnings.append(
            f"Estimated cost is ${total_cost:.2f} USD. "
            "Consider using the Budget tier to reduce costs."
        )

    return JobEstimateResponse(
        estimated_tokens_total=total_tokens,
        estimated_cost_usd=round(total_cost, 4),
        estimated_duration_minutes=round(total_duration_s / 60, 1),
        breakdown_by_agent=breakdown,
        warnings=warnings,
    )
