import re
import logging
from pathlib import Path
from typing import Dict, List, Any

logger = logging.getLogger(__name__)

class DynamicClassifier:
    """
    Assigns architectural roles to files using induced rules and heuristics.
    Prioritizes project-specific rules generated by the ArchitecturalInductor.
    """

    def __init__(self, induced_schema: Dict[str, Any] | None = None):
        self.schema = induced_schema or {}
        self.assignment_rules = self.schema.get("assignment_rules", [])
        self.zone_rules = self.schema.get("zone_rules", [])
        
        # Base fallback heuristics (from original HeuristicClassifier)
        self.BASE_PATTERNS = {
            "controller": [r"controller", r"api", r"route", r"handler"],
            "service": [r"service", r"provider", r"logic", r"business"],
            "repository": [r"repository", r"repo", r"dao", r"store"],
            "model": [r"entity", r"model", r"schema", r"domain"],
            "dto": [r"dto", r"contract", r"request", r"response", r"payload"],
            "test": [r"test", r"spec", r"mock", r"fixture"],
            "utility": [r"util", r"helper", r"tool", r"shared", r"common"],
        }

    def classify(self, file_path: Path, file_signals: Dict[str, Any] | None = None) -> Dict[str, Any]:
        """
        Classifies a file based on induced rules, zone rules, and base heuristics.
        """
        name = file_path.name.lower()
        rel_path = str(file_path).lower()
        signals = file_signals or {"imports": set(), "decorators": set(), "inheritance": set()}
        
        best_role = "unknown"
        best_confidence = 0.0
        reasoning = "Initial state."

        # 1. Apply Zone Rules (Directory-based)
        for zone in self.zone_rules:
            if rel_path.startswith(zone["dir_path"].lower()):
                if zone["confidence"] > best_confidence:
                    best_role = zone["assign_role"]
                    best_confidence = zone["confidence"]
                    reasoning = f"Matched zone rule for directory '{zone['dir_path']}'."

        # 2. Apply Assignment Rules (Signal-based)
        for rule in self.assignment_rules:
            signal = rule["if_signal"].lower()
            sig_type = rule["signal_type"]
            
            match = False
            if sig_type == "import" and any(signal in i.lower() for i in signals.get("imports", [])):
                match = True
            elif sig_type == "decorator" and any(signal in d.lower() for d in signals.get("decorators", [])):
                match = True
            elif sig_type == "inheritance" and any(signal in h.lower() for h in signals.get("inheritance", [])):
                match = True
            elif sig_type == "path" and re.search(signal, rel_path):
                match = True

            if match:
                # Signal matches are high confidence
                conf = rule.get("confidence", 0.8)
                if conf > best_confidence:
                    best_role = rule["assign_role"]
                    best_confidence = conf
                    reasoning = f"Induced rule matched signal '{signal}' ({sig_type})."

        # 3. Fallback to Base Heuristics (if confidence is low)
        if best_confidence < 0.5:
            for role, patterns in self.BASE_PATTERNS.items():
                for p in patterns:
                    if re.search(p, name) or (len(rel_path.split("/")) > 1 and re.search(p, rel_path)):
                        score = 0.5
                        if name.endswith(f"{p}.py") or name.endswith(f"{p}.ts"):
                            score += 0.2
                        
                        if score > best_confidence:
                            best_role = role
                            best_confidence = score
                            reasoning = f"Fallback heuristic: matched pattern '{p}'."

        # 4. Entrypoint Special Case
        if best_confidence < 0.8 and name in ["main.py", "app.py", "index.ts", "index.js", "server.js"]:
            best_role = "entrypoint"
            best_confidence = 0.9
            reasoning = "Universal entrypoint filename pattern."

        return {
            "role": best_role,
            "confidence": min(best_confidence, 1.0),
            "reasoning": reasoning
        }
